using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Drawing;

namespace BarbarianCall.Types
{
    static class VehicleColor
    {
        public enum EVehicleColor
        {
            MetallicBlack,
            MetallicGraphiteBlack,
            MetallicBlackSteal,
            MetallicDarkSilver,
            MetallicSilver,
            MetallicBlueSilver,
            MetallicSteelGray,
            MetallicShadowSilver,
            MetallicStoneSilver,
            MetallicMidnightSilver,
            MetallicGunMetal,
            MetallicAnthraciteGrey,
            MatteBlack,
            MatteGray,
            MatteLightGrey,
            UtilBlack,
            UtilBlackPoly,
            UtilDarksilver,
            UtilSilver,
            UtilGunMetal,
            UtilShadowSilver,
            WornBlack,
            WornGraphite,
            WornSilverGrey,
            WornSilver,
            WornBlueSilver,
            WornShadowSilver,
            MetallicRed,
            MetallicTorinoRed,
            MetallicFormulaRed,
            MetallicBlazeRed,
            MetallicGracefulRed,
            MetallicGarnetRed,
            MetallicDesertRed,
            MetallicCabernetRed,
            MetallicCandyRed,
            MetallicSunriseOrange,
            MetallicClassicGold,
            MetallicOrange,
            MatteRed,
            MatteDarkRed,
            MatteOrange,
            MatteYellow,
            UtilRed,
            UtilBrightRed,
            UtilGarnetRed,
            WornRed,
            WornGoldenRed,
            WornDarkRed,
            MetallicDarkGreen,
            MetallicRacingGreen,
            MetallicSeaGreen,
            MetallicOliveGreen,
            MetallicGreen,
            MetallicGasolineBlueGreen,
            MatteLimeGreen,
            UtilDarkGreen,
            UtilGreen,
            WornDarkGreen,
            WornGreen,
            WornSeaWash,
            MetallicMidnightBlue,
            MetallicDarkBlue,
            MetallicSaxonyBlue,
            MetallicBlue,
            MetallicMarinerBlue,
            MetallicHarborBlue,
            MetallicDiamondBlue,
            MetallicSurfBlue,
            MetallicNauticalBlue,
            MetallicBrightBlue2,
            MetallicPurpleBlue,
            MetallicSpinnakerBlue,
            MetallicUltraBlue,
            MetallicBrightBlue,
            UtilDarkBlue,
            UtilMidnightBlue,
            UtilBlue,
            UtilSeaFoamBlue,
            UtilLightningblue,
            UtilMauiBluePoly,
            UtilBrightBlue,
            MatteDarkBlue,
            MatteBlue,
            MatteMidnightBlue,
            WornDarkblue,
            WornBlue,
            WornLightblue,
            MetallicTaxiYellow,
            MetallicRaceYellow,
            MetallicBronze,
            MetallicYellowBird,
            MetallicLime,
            MetallicChampagne,
            MetallicPuebloBeige,
            MetallicDarkIvory,
            MetallicChocoBrown,
            MetallicGoldenBrown,
            MetallicLightBrown,
            MetallicStrawBeige,
            MetallicMossBrown,
            MetallicBistonBrown,
            MetallicBeechwood,
            MetallicDarkBeechwood,
            MetallicChocoOrange,
            MetallicBeachSand,
            MetallicSunBleechedSand,
            MetallicCream,
            UtilBrown,
            UtilMediumBrown,
            UtilLightBrown,
            MetallicWhite,
            MetallicFrostWhite,
            WornHoneyBeige,
            WornBrown,
            WornDarkBrown,
            Wornstrawbeige,
            BrushedSteel,
            BrushedBlacksteel,
            BrushedAluminium,
            Chrome,
            WornOffWhite,
            UtilOffWhite,
            WornOrange,
            WornLightOrange,
            MetallicSecuricorGreen,
            WornTaxiYellow,
            policecarblue,
            MatteGreen,
            MatteBrown,
            WornOrange2,
            MatteWhite,
            WornWhite,
            WornOliveArmyGreen,
            PureWhite,
            HotPink,
            Salmonpink,
            MetallicVermillionPink,
            Orange,
            Green,
            Blue,
            MettalicBlackBlue,
            MetallicBlackPurple,
            MetallicBlackRed,
            huntergreen,
            MetallicPurple,
            MetaillicVDarkBlue,
            MODSHOPBLACK1,
            MattePurple,
            MatteDarkPurple,
            MetallicLavaRed,
            MatteForestGreen,
            MatteOliveDrab,
            MatteDesertBrown,
            MatteDesertTan,
            MatteFoilageGreen,
            DEFAULTALLOYCOLOR,
            EpsilonBlue,
            PureGold,
            BrushedGold,
            UnknownColor,
        }
        public static Color GetColor(this EVehicleColor vehicleColor) => vehicleColor switch
        {
            EVehicleColor.MetallicBlack => Color.FromArgb(13, 17, 22),
            EVehicleColor.MetallicGraphiteBlack => Color.FromArgb(28, 29, 33),
            EVehicleColor.MetallicBlackSteal => Color.FromArgb(50, 56, 61),
            EVehicleColor.MetallicDarkSilver => Color.FromArgb(69, 75, 79),
            EVehicleColor.MetallicSilver => Color.FromArgb(153, 157, 160),
            EVehicleColor.MetallicBlueSilver => Color.FromArgb(194, 196, 198),
            EVehicleColor.MetallicSteelGray => Color.FromArgb(151, 154, 151),
            EVehicleColor.MetallicShadowSilver => Color.FromArgb(99, 115, 128),
            EVehicleColor.MetallicStoneSilver => Color.FromArgb(99, 98, 92),
            EVehicleColor.MetallicMidnightSilver => Color.FromArgb(60, 63, 71),
            EVehicleColor.MetallicGunMetal => Color.FromArgb(68, 78, 84),
            EVehicleColor.MetallicAnthraciteGrey => Color.FromArgb(29, 33, 41),
            EVehicleColor.MatteBlack => Color.FromArgb(19, 24, 31),
            EVehicleColor.MatteGray => Color.FromArgb(38, 40, 42),
            EVehicleColor.MatteLightGrey => Color.FromArgb(81, 85, 84),
            EVehicleColor.UtilBlack => Color.FromArgb(21, 25, 33),
            EVehicleColor.UtilBlackPoly => Color.FromArgb(30, 36, 41),
            EVehicleColor.UtilDarksilver => Color.FromArgb(51, 58, 60),
            EVehicleColor.UtilSilver => Color.FromArgb(140, 144, 149),
            EVehicleColor.UtilGunMetal => Color.FromArgb(57, 67, 77),
            EVehicleColor.UtilShadowSilver => Color.FromArgb(80, 98, 114),
            EVehicleColor.WornBlack => Color.FromArgb(30, 35, 47),
            EVehicleColor.WornGraphite => Color.FromArgb(54, 58, 63),
            EVehicleColor.WornSilverGrey => Color.FromArgb(160, 161, 153),
            EVehicleColor.WornSilver => Color.FromArgb(211, 211, 211),
            EVehicleColor.WornBlueSilver => Color.FromArgb(183, 191, 202),
            EVehicleColor.WornShadowSilver => Color.FromArgb(119, 135, 148),
            EVehicleColor.MetallicRed => Color.FromArgb(192, 14, 26),
            EVehicleColor.MetallicTorinoRed => Color.FromArgb(218, 25, 24),
            EVehicleColor.MetallicFormulaRed => Color.FromArgb(182, 17, 27),
            EVehicleColor.MetallicBlazeRed => Color.FromArgb(165, 30, 35),
            EVehicleColor.MetallicGracefulRed => Color.FromArgb(123, 26, 34),
            EVehicleColor.MetallicGarnetRed => Color.FromArgb(142, 27, 31),
            EVehicleColor.MetallicDesertRed => Color.FromArgb(111, 24, 24),
            EVehicleColor.MetallicCabernetRed => Color.FromArgb(73, 17, 29),
            EVehicleColor.MetallicCandyRed => Color.FromArgb(182, 15, 37),
            EVehicleColor.MetallicSunriseOrange => Color.FromArgb(212, 74, 23),
            EVehicleColor.MetallicClassicGold => Color.FromArgb(194, 148, 79),
            EVehicleColor.MetallicOrange => Color.FromArgb(247, 134, 22),
            EVehicleColor.MatteRed => Color.FromArgb(207, 31, 33),
            EVehicleColor.MatteDarkRed => Color.FromArgb(115, 32, 33),
            EVehicleColor.MatteOrange => Color.FromArgb(242, 125, 32),
            EVehicleColor.MatteYellow => Color.FromArgb(255, 201, 31),
            EVehicleColor.UtilRed => Color.FromArgb(156, 16, 22),
            EVehicleColor.UtilBrightRed => Color.FromArgb(222, 15, 24),
            EVehicleColor.UtilGarnetRed => Color.FromArgb(143, 30, 23),
            EVehicleColor.WornRed => Color.FromArgb(169, 71, 68),
            EVehicleColor.WornGoldenRed => Color.FromArgb(177, 108, 81),
            EVehicleColor.WornDarkRed => Color.FromArgb(55, 28, 37),
            EVehicleColor.MetallicDarkGreen => Color.FromArgb(19, 36, 40),
            EVehicleColor.MetallicRacingGreen => Color.FromArgb(18, 46, 43),
            EVehicleColor.MetallicSeaGreen => Color.FromArgb(18, 56, 60),
            EVehicleColor.MetallicOliveGreen => Color.FromArgb(49, 66, 63),
            EVehicleColor.MetallicGreen => Color.FromArgb(21, 92, 45),
            EVehicleColor.MetallicGasolineBlueGreen => Color.FromArgb(27, 103, 112),
            EVehicleColor.MatteLimeGreen => Color.FromArgb(102, 184, 31),
            EVehicleColor.UtilDarkGreen => Color.FromArgb(34, 56, 62),
            EVehicleColor.UtilGreen => Color.FromArgb(29, 90, 63),
            EVehicleColor.WornDarkGreen => Color.FromArgb(45, 66, 63),
            EVehicleColor.WornGreen => Color.FromArgb(69, 89, 75),
            EVehicleColor.WornSeaWash => Color.FromArgb(101, 134, 127),
            EVehicleColor.MetallicMidnightBlue => Color.FromArgb(34, 46, 70),
            EVehicleColor.MetallicDarkBlue => Color.FromArgb(35, 49, 85),
            EVehicleColor.MetallicSaxonyBlue => Color.FromArgb(48, 76, 126),
            EVehicleColor.MetallicBlue => Color.FromArgb(71, 87, 143),
            EVehicleColor.MetallicMarinerBlue => Color.FromArgb(99, 123, 167),
            EVehicleColor.MetallicHarborBlue => Color.FromArgb(57, 71, 98),
            EVehicleColor.MetallicDiamondBlue => Color.FromArgb(214, 231, 241),
            EVehicleColor.MetallicSurfBlue => Color.FromArgb(118, 175, 190),
            EVehicleColor.MetallicNauticalBlue => Color.FromArgb(52, 94, 114),
            EVehicleColor.MetallicBrightBlue2 => Color.FromArgb(11, 156, 241),
            EVehicleColor.MetallicPurpleBlue => Color.FromArgb(47, 45, 82),
            EVehicleColor.MetallicSpinnakerBlue => Color.FromArgb(40, 44, 77),
            EVehicleColor.MetallicUltraBlue => Color.FromArgb(35, 84, 161),
            EVehicleColor.MetallicBrightBlue => Color.FromArgb(110, 163, 198),
            EVehicleColor.UtilDarkBlue => Color.FromArgb(17, 37, 82),
            EVehicleColor.UtilMidnightBlue => Color.FromArgb(27, 32, 62),
            EVehicleColor.UtilBlue => Color.FromArgb(39, 81, 144),
            EVehicleColor.UtilSeaFoamBlue => Color.FromArgb(96, 133, 146),
            EVehicleColor.UtilLightningblue => Color.FromArgb(36, 70, 168),
            EVehicleColor.UtilMauiBluePoly => Color.FromArgb(66, 113, 225),
            EVehicleColor.UtilBrightBlue => Color.FromArgb(59, 57, 224),
            EVehicleColor.MatteDarkBlue => Color.FromArgb(31, 40, 82),
            EVehicleColor.MatteBlue => Color.FromArgb(37, 58, 167),
            EVehicleColor.MatteMidnightBlue => Color.FromArgb(28, 53, 81),
            EVehicleColor.WornDarkblue => Color.FromArgb(76, 95, 129),
            EVehicleColor.WornBlue => Color.FromArgb(88, 104, 142),
            EVehicleColor.WornLightblue => Color.FromArgb(116, 181, 216),
            EVehicleColor.MetallicTaxiYellow => Color.FromArgb(255, 207, 32),
            EVehicleColor.MetallicRaceYellow => Color.FromArgb(251, 226, 18),
            EVehicleColor.MetallicBronze => Color.FromArgb(145, 101, 50),
            EVehicleColor.MetallicYellowBird => Color.FromArgb(224, 225, 61),
            EVehicleColor.MetallicLime => Color.FromArgb(152, 210, 35),
            EVehicleColor.MetallicChampagne => Color.FromArgb(155, 140, 120),
            EVehicleColor.MetallicPuebloBeige => Color.FromArgb(80, 50, 24),
            EVehicleColor.MetallicDarkIvory => Color.FromArgb(71, 63, 43),
            EVehicleColor.MetallicChocoBrown => Color.FromArgb(34, 27, 25),
            EVehicleColor.MetallicGoldenBrown => Color.FromArgb(101, 63, 35),
            EVehicleColor.MetallicLightBrown => Color.FromArgb(119, 92, 62),
            EVehicleColor.MetallicStrawBeige => Color.FromArgb(172, 153, 117),
            EVehicleColor.MetallicMossBrown => Color.FromArgb(108, 107, 75),
            EVehicleColor.MetallicBistonBrown => Color.FromArgb(64, 46, 43),
            EVehicleColor.MetallicBeechwood => Color.FromArgb(164, 150, 95),
            EVehicleColor.MetallicDarkBeechwood => Color.FromArgb(70, 35, 26),
            EVehicleColor.MetallicChocoOrange => Color.FromArgb(117, 43, 25),
            EVehicleColor.MetallicBeachSand => Color.FromArgb(191, 174, 123),
            EVehicleColor.MetallicSunBleechedSand => Color.FromArgb(223, 213, 178),
            EVehicleColor.MetallicCream => Color.FromArgb(247, 237, 213),
            EVehicleColor.UtilBrown => Color.FromArgb(58, 42, 27),
            EVehicleColor.UtilMediumBrown => Color.FromArgb(120, 95, 51),
            EVehicleColor.UtilLightBrown => Color.FromArgb(181, 160, 121),
            EVehicleColor.MetallicWhite => Color.FromArgb(255, 255, 246),
            EVehicleColor.MetallicFrostWhite => Color.FromArgb(234, 234, 234),
            EVehicleColor.WornHoneyBeige => Color.FromArgb(176, 171, 148),
            EVehicleColor.WornBrown => Color.FromArgb(69, 56, 49),
            EVehicleColor.WornDarkBrown => Color.FromArgb(42, 40, 43),
            EVehicleColor.Wornstrawbeige => Color.FromArgb(114, 108, 87),
            EVehicleColor.BrushedSteel => Color.FromArgb(106, 116, 124),
            EVehicleColor.BrushedBlacksteel => Color.FromArgb(53, 65, 88),
            EVehicleColor.BrushedAluminium => Color.FromArgb(155, 160, 168),
            EVehicleColor.Chrome => Color.FromArgb(88, 112, 161),
            EVehicleColor.WornOffWhite => Color.FromArgb(234, 230, 222),
            EVehicleColor.UtilOffWhite => Color.FromArgb(223, 221, 208),
            EVehicleColor.WornOrange => Color.FromArgb(242, 173, 46),
            EVehicleColor.WornLightOrange => Color.FromArgb(249, 164, 88),
            EVehicleColor.MetallicSecuricorGreen => Color.FromArgb(131, 197, 102),
            EVehicleColor.WornTaxiYellow => Color.FromArgb(241, 204, 64),
            EVehicleColor.policecarblue => Color.FromArgb(76, 195, 218),
            EVehicleColor.MatteGreen => Color.FromArgb(78, 100, 67),
            EVehicleColor.MatteBrown => Color.FromArgb(188, 172, 143),
            EVehicleColor.WornOrange2 => Color.FromArgb(248, 182, 88),
            EVehicleColor.MatteWhite => Color.FromArgb(252, 249, 241),
            EVehicleColor.WornWhite => Color.FromArgb(255, 255, 251),
            EVehicleColor.WornOliveArmyGreen => Color.FromArgb(129, 132, 76),
            EVehicleColor.PureWhite => Color.FromArgb(255, 255, 255),
            EVehicleColor.HotPink => Color.FromArgb(242, 31, 153),
            EVehicleColor.Salmonpink => Color.FromArgb(253, 214, 205),
            EVehicleColor.MetallicVermillionPink => Color.FromArgb(223, 88, 145),
            EVehicleColor.Orange => Color.FromArgb(246, 174, 32),
            EVehicleColor.Green => Color.FromArgb(176, 238, 110),
            EVehicleColor.Blue => Color.FromArgb(8, 233, 250),
            EVehicleColor.MettalicBlackBlue => Color.FromArgb(10, 12, 23),
            EVehicleColor.MetallicBlackPurple => Color.FromArgb(12, 13, 24),
            EVehicleColor.MetallicBlackRed => Color.FromArgb(14, 13, 20),
            EVehicleColor.huntergreen => Color.FromArgb(159, 158, 138),
            EVehicleColor.MetallicPurple => Color.FromArgb(98, 18, 118),
            EVehicleColor.MetaillicVDarkBlue => Color.FromArgb(11, 20, 33),
            EVehicleColor.MODSHOPBLACK1 => Color.FromArgb(17, 20, 26),
            EVehicleColor.MattePurple => Color.FromArgb(107, 31, 123),
            EVehicleColor.MatteDarkPurple => Color.FromArgb(30, 29, 34),
            EVehicleColor.MetallicLavaRed => Color.FromArgb(188, 25, 23),
            EVehicleColor.MatteForestGreen => Color.FromArgb(45, 54, 42),
            EVehicleColor.MatteOliveDrab => Color.FromArgb(105, 103, 72),
            EVehicleColor.MatteDesertBrown => Color.FromArgb(122, 108, 85),
            EVehicleColor.MatteDesertTan => Color.FromArgb(195, 180, 146),
            EVehicleColor.MatteFoilageGreen => Color.FromArgb(90, 99, 82),
            EVehicleColor.DEFAULTALLOYCOLOR => Color.FromArgb(129, 130, 127),
            EVehicleColor.EpsilonBlue => Color.FromArgb(175, 214, 228),
            EVehicleColor.PureGold => Color.FromArgb(122, 100, 64),
            EVehicleColor.BrushedGold => Color.FromArgb(127, 106, 72),
            _ => Color.Transparent,
        };
        public static EVehicleColor FromPrimaryVehicle(Rage.Vehicle vehicle)
        {
            Rage.Native.NativeFunction.Natives.GET_VEHICLE_COLOURS(vehicle, out int primary, out int _);
            return (EVehicleColor)primary;
        }
    }
}
