using System;
using System.Drawing;

namespace BarbarianCall.Extensions
{
    internal static class ColorExtension
    {
        public static Color GetColor(this VehicleColor vehicleColor) => vehicleColor switch
        {
            VehicleColor.MetallicBlack => Color.FromArgb(13, 17, 22),
            VehicleColor.MetallicGraphiteBlack => Color.FromArgb(28, 29, 33),
            VehicleColor.MetallicBlackSteal => Color.FromArgb(50, 56, 61),
            VehicleColor.MetallicDarkSilver => Color.FromArgb(69, 75, 79),
            VehicleColor.MetallicSilver => Color.FromArgb(153, 157, 160),
            VehicleColor.MetallicBlueSilver => Color.FromArgb(194, 196, 198),
            VehicleColor.MetallicSteelGray => Color.FromArgb(151, 154, 151),
            VehicleColor.MetallicShadowSilver => Color.FromArgb(99, 115, 128),
            VehicleColor.MetallicStoneSilver => Color.FromArgb(99, 98, 92),
            VehicleColor.MetallicMidnightSilver => Color.FromArgb(60, 63, 71),
            VehicleColor.MetallicGunMetal => Color.FromArgb(68, 78, 84),
            VehicleColor.MetallicAnthraciteGrey => Color.FromArgb(29, 33, 41),
            VehicleColor.MatteBlack => Color.FromArgb(19, 24, 31),
            VehicleColor.MatteGray => Color.FromArgb(38, 40, 42),
            VehicleColor.MatteLightGrey => Color.FromArgb(81, 85, 84),
            VehicleColor.UtilBlack => Color.FromArgb(21, 25, 33),
            VehicleColor.UtilBlackPoly => Color.FromArgb(30, 36, 41),
            VehicleColor.UtilDarksilver => Color.FromArgb(51, 58, 60),
            VehicleColor.UtilSilver => Color.FromArgb(140, 144, 149),
            VehicleColor.UtilGunMetal => Color.FromArgb(57, 67, 77),
            VehicleColor.UtilShadowSilver => Color.FromArgb(80, 98, 114),
            VehicleColor.WornBlack => Color.FromArgb(30, 35, 47),
            VehicleColor.WornGraphite => Color.FromArgb(54, 58, 63),
            VehicleColor.WornSilverGrey => Color.FromArgb(160, 161, 153),
            VehicleColor.WornSilver => Color.FromArgb(211, 211, 211),
            VehicleColor.WornBlueSilver => Color.FromArgb(183, 191, 202),
            VehicleColor.WornShadowSilver => Color.FromArgb(119, 135, 148),
            VehicleColor.MetallicRed => Color.FromArgb(192, 14, 26),
            VehicleColor.MetallicTorinoRed => Color.FromArgb(218, 25, 24),
            VehicleColor.MetallicFormulaRed => Color.FromArgb(182, 17, 27),
            VehicleColor.MetallicBlazeRed => Color.FromArgb(165, 30, 35),
            VehicleColor.MetallicGracefulRed => Color.FromArgb(123, 26, 34),
            VehicleColor.MetallicGarnetRed => Color.FromArgb(142, 27, 31),
            VehicleColor.MetallicDesertRed => Color.FromArgb(111, 24, 24),
            VehicleColor.MetallicCabernetRed => Color.FromArgb(73, 17, 29),
            VehicleColor.MetallicCandyRed => Color.FromArgb(182, 15, 37),
            VehicleColor.MetallicSunriseOrange => Color.FromArgb(212, 74, 23),
            VehicleColor.MetallicClassicGold => Color.FromArgb(194, 148, 79),
            VehicleColor.MetallicOrange => Color.FromArgb(247, 134, 22),
            VehicleColor.MatteRed => Color.FromArgb(207, 31, 33),
            VehicleColor.MatteDarkRed => Color.FromArgb(115, 32, 33),
            VehicleColor.MatteOrange => Color.FromArgb(242, 125, 32),
            VehicleColor.MatteYellow => Color.FromArgb(255, 201, 31),
            VehicleColor.UtilRed => Color.FromArgb(156, 16, 22),
            VehicleColor.UtilBrightRed => Color.FromArgb(222, 15, 24),
            VehicleColor.UtilGarnetRed => Color.FromArgb(143, 30, 23),
            VehicleColor.WornRed => Color.FromArgb(169, 71, 68),
            VehicleColor.WornGoldenRed => Color.FromArgb(177, 108, 81),
            VehicleColor.WornDarkRed => Color.FromArgb(55, 28, 37),
            VehicleColor.MetallicDarkGreen => Color.FromArgb(19, 36, 40),
            VehicleColor.MetallicRacingGreen => Color.FromArgb(18, 46, 43),
            VehicleColor.MetallicSeaGreen => Color.FromArgb(18, 56, 60),
            VehicleColor.MetallicOliveGreen => Color.FromArgb(49, 66, 63),
            VehicleColor.MetallicGreen => Color.FromArgb(21, 92, 45),
            VehicleColor.MetallicGasolineBlueGreen => Color.FromArgb(27, 103, 112),
            VehicleColor.MatteLimeGreen => Color.FromArgb(102, 184, 31),
            VehicleColor.UtilDarkGreen => Color.FromArgb(34, 56, 62),
            VehicleColor.UtilGreen => Color.FromArgb(29, 90, 63),
            VehicleColor.WornDarkGreen => Color.FromArgb(45, 66, 63),
            VehicleColor.WornGreen => Color.FromArgb(69, 89, 75),
            VehicleColor.WornSeaWash => Color.FromArgb(101, 134, 127),
            VehicleColor.MetallicMidnightBlue => Color.FromArgb(34, 46, 70),
            VehicleColor.MetallicDarkBlue => Color.FromArgb(35, 49, 85),
            VehicleColor.MetallicSaxonyBlue => Color.FromArgb(48, 76, 126),
            VehicleColor.MetallicBlue => Color.FromArgb(71, 87, 143),
            VehicleColor.MetallicMarinerBlue => Color.FromArgb(99, 123, 167),
            VehicleColor.MetallicHarborBlue => Color.FromArgb(57, 71, 98),
            VehicleColor.MetallicDiamondBlue => Color.FromArgb(214, 231, 241),
            VehicleColor.MetallicSurfBlue => Color.FromArgb(118, 175, 190),
            VehicleColor.MetallicNauticalBlue => Color.FromArgb(52, 94, 114),
            VehicleColor.MetallicBrightBlue2 => Color.FromArgb(11, 156, 241),
            VehicleColor.MetallicPurpleBlue => Color.FromArgb(47, 45, 82),
            VehicleColor.MetallicSpinnakerBlue => Color.FromArgb(40, 44, 77),
            VehicleColor.MetallicUltraBlue => Color.FromArgb(35, 84, 161),
            VehicleColor.MetallicBrightBlue => Color.FromArgb(110, 163, 198),
            VehicleColor.UtilDarkBlue => Color.FromArgb(17, 37, 82),
            VehicleColor.UtilMidnightBlue => Color.FromArgb(27, 32, 62),
            VehicleColor.UtilBlue => Color.FromArgb(39, 81, 144),
            VehicleColor.UtilSeaFoamBlue => Color.FromArgb(96, 133, 146),
            VehicleColor.UtilLightningblue => Color.FromArgb(36, 70, 168),
            VehicleColor.UtilMauiBluePoly => Color.FromArgb(66, 113, 225),
            VehicleColor.UtilBrightBlue => Color.FromArgb(59, 57, 224),
            VehicleColor.MatteDarkBlue => Color.FromArgb(31, 40, 82),
            VehicleColor.MatteBlue => Color.FromArgb(37, 58, 167),
            VehicleColor.MatteMidnightBlue => Color.FromArgb(28, 53, 81),
            VehicleColor.WornDarkblue => Color.FromArgb(76, 95, 129),
            VehicleColor.WornBlue => Color.FromArgb(88, 104, 142),
            VehicleColor.WornLightblue => Color.FromArgb(116, 181, 216),
            VehicleColor.MetallicTaxiYellow => Color.FromArgb(255, 207, 32),
            VehicleColor.MetallicRaceYellow => Color.FromArgb(251, 226, 18),
            VehicleColor.MetallicBronze => Color.FromArgb(145, 101, 50),
            VehicleColor.MetallicYellowBird => Color.FromArgb(224, 225, 61),
            VehicleColor.MetallicLime => Color.FromArgb(152, 210, 35),
            VehicleColor.MetallicChampagne => Color.FromArgb(155, 140, 120),
            VehicleColor.MetallicPuebloBeige => Color.FromArgb(80, 50, 24),
            VehicleColor.MetallicDarkIvory => Color.FromArgb(71, 63, 43),
            VehicleColor.MetallicChocoBrown => Color.FromArgb(34, 27, 25),
            VehicleColor.MetallicGoldenBrown => Color.FromArgb(101, 63, 35),
            VehicleColor.MetallicLightBrown => Color.FromArgb(119, 92, 62),
            VehicleColor.MetallicStrawBeige => Color.FromArgb(172, 153, 117),
            VehicleColor.MetallicMossBrown => Color.FromArgb(108, 107, 75),
            VehicleColor.MetallicBistonBrown => Color.FromArgb(64, 46, 43),
            VehicleColor.MetallicBeechwood => Color.FromArgb(164, 150, 95),
            VehicleColor.MetallicDarkBeechwood => Color.FromArgb(70, 35, 26),
            VehicleColor.MetallicChocoOrange => Color.FromArgb(117, 43, 25),
            VehicleColor.MetallicBeachSand => Color.FromArgb(191, 174, 123),
            VehicleColor.MetallicSunBleechedSand => Color.FromArgb(223, 213, 178),
            VehicleColor.MetallicCream => Color.FromArgb(247, 237, 213),
            VehicleColor.UtilBrown => Color.FromArgb(58, 42, 27),
            VehicleColor.UtilMediumBrown => Color.FromArgb(120, 95, 51),
            VehicleColor.UtilLightBrown => Color.FromArgb(181, 160, 121),
            VehicleColor.MetallicWhite => Color.FromArgb(255, 255, 246),
            VehicleColor.MetallicFrostWhite => Color.FromArgb(234, 234, 234),
            VehicleColor.WornHoneyBeige => Color.FromArgb(176, 171, 148),
            VehicleColor.WornBrown => Color.FromArgb(69, 56, 49),
            VehicleColor.WornDarkBrown => Color.FromArgb(42, 40, 43),
            VehicleColor.Wornstrawbeige => Color.FromArgb(114, 108, 87),
            VehicleColor.BrushedSteel => Color.FromArgb(106, 116, 124),
            VehicleColor.BrushedBlacksteel => Color.FromArgb(53, 65, 88),
            VehicleColor.BrushedAluminium => Color.FromArgb(155, 160, 168),
            VehicleColor.Chrome => Color.FromArgb(88, 112, 161),
            VehicleColor.WornOffWhite => Color.FromArgb(234, 230, 222),
            VehicleColor.UtilOffWhite => Color.FromArgb(223, 221, 208),
            VehicleColor.WornOrange => Color.FromArgb(242, 173, 46),
            VehicleColor.WornLightOrange => Color.FromArgb(249, 164, 88),
            VehicleColor.MetallicSecuricorGreen => Color.FromArgb(131, 197, 102),
            VehicleColor.WornTaxiYellow => Color.FromArgb(241, 204, 64),
            VehicleColor.policecarblue => Color.FromArgb(76, 195, 218),
            VehicleColor.MatteGreen => Color.FromArgb(78, 100, 67),
            VehicleColor.MatteBrown => Color.FromArgb(188, 172, 143),
            VehicleColor.WornOrange2 => Color.FromArgb(248, 182, 88),
            VehicleColor.MatteWhite => Color.FromArgb(252, 249, 241),
            VehicleColor.WornWhite => Color.FromArgb(255, 255, 251),
            VehicleColor.WornOliveArmyGreen => Color.FromArgb(129, 132, 76),
            VehicleColor.PureWhite => Color.FromArgb(255, 255, 255),
            VehicleColor.HotPink => Color.FromArgb(242, 31, 153),
            VehicleColor.Salmonpink => Color.FromArgb(253, 214, 205),
            VehicleColor.MetallicVermillionPink => Color.FromArgb(223, 88, 145),
            VehicleColor.Orange => Color.FromArgb(246, 174, 32),
            VehicleColor.Green => Color.FromArgb(176, 238, 110),
            VehicleColor.Blue => Color.FromArgb(8, 233, 250),
            VehicleColor.MettalicBlackBlue => Color.FromArgb(10, 12, 23),
            VehicleColor.MetallicBlackPurple => Color.FromArgb(12, 13, 24),
            VehicleColor.MetallicBlackRed => Color.FromArgb(14, 13, 20),
            VehicleColor.huntergreen => Color.FromArgb(159, 158, 138),
            VehicleColor.MetallicPurple => Color.FromArgb(98, 18, 118),
            VehicleColor.MetaillicVDarkBlue => Color.FromArgb(11, 20, 33),
            VehicleColor.MODSHOPBLACK1 => Color.FromArgb(17, 20, 26),
            VehicleColor.MattePurple => Color.FromArgb(107, 31, 123),
            VehicleColor.MatteDarkPurple => Color.FromArgb(30, 29, 34),
            VehicleColor.MetallicLavaRed => Color.FromArgb(188, 25, 23),
            VehicleColor.MatteForestGreen => Color.FromArgb(45, 54, 42),
            VehicleColor.MatteOliveDrab => Color.FromArgb(105, 103, 72),
            VehicleColor.MatteDesertBrown => Color.FromArgb(122, 108, 85),
            VehicleColor.MatteDesertTan => Color.FromArgb(195, 180, 146),
            VehicleColor.MatteFoilageGreen => Color.FromArgb(90, 99, 82),
            VehicleColor.DEFAULTALLOYCOLOR => Color.FromArgb(129, 130, 127),
            VehicleColor.EpsilonBlue => Color.FromArgb(175, 214, 228),
            VehicleColor.PureGold => Color.FromArgb(122, 100, 64),
            VehicleColor.BrushedGold => Color.FromArgb(127, 106, 72),
            _ => throw new ArgumentOutOfRangeException(nameof(vehicleColor), vehicleColor, $"Invalid {nameof(vehicleColor)}")
        };
    }
    public enum VehicleColor
    {
        MetallicBlack,
        MetallicGraphiteBlack,
        MetallicBlackSteal,
        MetallicDarkSilver,
        MetallicSilver,
        MetallicBlueSilver,
        MetallicSteelGray,
        MetallicShadowSilver,
        MetallicStoneSilver,
        MetallicMidnightSilver,
        MetallicGunMetal,
        MetallicAnthraciteGrey,
        MatteBlack,
        MatteGray,
        MatteLightGrey,
        UtilBlack,
        UtilBlackPoly,
        UtilDarksilver,
        UtilSilver,
        UtilGunMetal,
        UtilShadowSilver,
        WornBlack,
        WornGraphite,
        WornSilverGrey,
        WornSilver,
        WornBlueSilver,
        WornShadowSilver,
        MetallicRed,
        MetallicTorinoRed,
        MetallicFormulaRed,
        MetallicBlazeRed,
        MetallicGracefulRed,
        MetallicGarnetRed,
        MetallicDesertRed,
        MetallicCabernetRed,
        MetallicCandyRed,
        MetallicSunriseOrange,
        MetallicClassicGold,
        MetallicOrange,
        MatteRed,
        MatteDarkRed,
        MatteOrange,
        MatteYellow,
        UtilRed,
        UtilBrightRed,
        UtilGarnetRed,
        WornRed,
        WornGoldenRed,
        WornDarkRed,
        MetallicDarkGreen,
        MetallicRacingGreen,
        MetallicSeaGreen,
        MetallicOliveGreen,
        MetallicGreen,
        MetallicGasolineBlueGreen,
        MatteLimeGreen,
        UtilDarkGreen,
        UtilGreen,
        WornDarkGreen,
        WornGreen,
        WornSeaWash,
        MetallicMidnightBlue,
        MetallicDarkBlue,
        MetallicSaxonyBlue,
        MetallicBlue,
        MetallicMarinerBlue,
        MetallicHarborBlue,
        MetallicDiamondBlue,
        MetallicSurfBlue,
        MetallicNauticalBlue,
        MetallicBrightBlue,
        MetallicPurpleBlue,
        MetallicSpinnakerBlue,
        MetallicUltraBlue,
        MetallicBrightBlue2,
        UtilDarkBlue,
        UtilMidnightBlue,
        UtilBlue,
        UtilSeaFoamBlue,
        UtilLightningblue,
        UtilMauiBluePoly,
        UtilBrightBlue,
        MatteDarkBlue,
        MatteBlue,
        MatteMidnightBlue,
        WornDarkblue,
        WornBlue,
        WornLightblue,
        MetallicTaxiYellow,
        MetallicRaceYellow,
        MetallicBronze,
        MetallicYellowBird,
        MetallicLime,
        MetallicChampagne,
        MetallicPuebloBeige,
        MetallicDarkIvory,
        MetallicChocoBrown,
        MetallicGoldenBrown,
        MetallicLightBrown,
        MetallicStrawBeige,
        MetallicMossBrown,
        MetallicBistonBrown,
        MetallicBeechwood,
        MetallicDarkBeechwood,
        MetallicChocoOrange,
        MetallicBeachSand,
        MetallicSunBleechedSand,
        MetallicCream,
        UtilBrown,
        UtilMediumBrown,
        UtilLightBrown,
        MetallicWhite,
        MetallicFrostWhite,
        WornHoneyBeige,
        WornBrown,
        WornDarkBrown,
        Wornstrawbeige,
        BrushedSteel,
        BrushedBlacksteel,
        BrushedAluminium,
        Chrome,
        WornOffWhite,
        UtilOffWhite,
        WornOrange,
        WornLightOrange,
        MetallicSecuricorGreen,
        WornTaxiYellow,
        policecarblue,
        MatteGreen,
        MatteBrown,
        WornOrange2,
        MatteWhite,
        WornWhite,
        WornOliveArmyGreen,
        PureWhite,
        HotPink,
        Salmonpink,
        MetallicVermillionPink,
        Orange,
        Green,
        Blue,
        MettalicBlackBlue,
        MetallicBlackPurple,
        MetallicBlackRed,
        huntergreen,
        MetallicPurple,
        MetaillicVDarkBlue,
        MODSHOPBLACK1,
        MattePurple,
        MatteDarkPurple,
        MetallicLavaRed,
        MatteForestGreen,
        MatteOliveDrab,
        MatteDesertBrown,
        MatteDesertTan,
        MatteFoilageGreen,
        DEFAULTALLOYCOLOR,
        EpsilonBlue,
        PureGold,
        BrushedGold,
    }
}
